version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - AZURE_SQL_CONNECTION=${AZURE_SQL_CONNECTION}

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5050/api
      - VITE_IMAGE_BASE_URL=http://localhost:5050
    depends_on:
      - backend
